[element_attributes]
tag = "CT0.7"
orientation = "vertical"
vert_correspondent_below = []
vert_correspondent_above = []
horz_intersects_above = [
    "FB0.3",
]
horz_intersects_below = []

[element_attributes.length]

[element_attributes.user_defined]

[element_geometry]
geometry = "POLYGON ((15.5881 28.9641, 15.5881 29.7268, 16.4119 29.7268, 16.4119 28.9641, 15.5881 28.9641))"
supports = []

[loads]
distributed_loads = []

[[loads.point_loads]]
location = 0.0
magnitude = 0.0
transfer_source = "FB0.3"
transfer_reaction_index = 0
direction = "gravity"
