[element_attributes]
tag = "FB0.2"
length = 7.9906
orientation = "horizontal"
vert_correspondent_below = []
vert_correspondent_above = []
horz_intersects_above = [
    "SJ0.0-0",
    "SJ0.0-1",
]
horz_intersects_below = [
    "CT0.8",
    "FB0.4",
]

[element_attributes.user_defined]

[element_geometry]
geometry = "LINESTRING (2.5798 29.3685, 10.5704 29.3685)"
supports = [
    { location = 7.6568, fixity = "pin" },
    { location = 2.6604, fixity = "roller" },
]

[loads]
point_loads = []

[[loads.distributed_loads]]
transfer_source = "SJ0.0-0"
transfer_reaction_index = 1
transfer_source_start_extent = []
transfer_source_end_extent = []
occupancy = ""
applied_area = 0.0
start_loc = 3.5401
start_magnitude = 1.0
end_loc = 4.8772
end_magnitude = 1.0
direction = "gravity"

[loads.distributed_loads.load_components]

[[loads.distributed_loads]]
transfer_source = "SJ0.0-1"
transfer_reaction_index = 2
transfer_source_start_extent = []
transfer_source_end_extent = []
occupancy = ""
applied_area = 0.0
start_loc = 4.8772
start_magnitude = 1.0
end_loc = 7.7392
end_magnitude = 1.0
direction = "gravity"

[loads.distributed_loads.load_components]
