[element_attributes]
tag = "SJ0.1"
length = 11.08
orientation = "horizontal"
vert_correspondent_below = []
vert_correspondent_above = []
horz_intersects_above = []
horz_intersects_below = [
    "FB0.1",
    "FB0.3",
]

[element_attributes.user_defined]

[element_geometry]
geometry = "LINESTRING (22.4727 18.3927, 22.4727 29.4727)"
supports = [
    { location = 0.3053, fixity = "pin" },
    { location = 11.035, fixity = "roller" },
]

[loads]
point_loads = []

[[loads.distributed_loads]]
transfer_source = ""
transfer_reaction_index = ""
occupancy = "roof"
load_components = []
applied_area = 10.6904
start_loc = 0.3896
start_magnitude = 0.0935
end_loc = 11.08
end_magnitude = 0.0935
