[element_attributes]
tag = "SJ0.0-6"
length = 11.2766
orientation = "horizontal"
vert_correspondent_below = []
vert_correspondent_above = []
horz_intersects_above = []
horz_intersects_below = [
    "FB0.1",
    "FB0.3",
]

[element_attributes.user_defined]

[element_geometry]
geometry = "LINESTRING (20.975 18.5681, 20.975 29.8447)"
supports = [
    { location = 0.1299, fixity = "pin" },
    { location = 10.8596, fixity = "roller" },
]

[loads]
point_loads = []

[[loads.distributed_loads]]
transfer_source = ""
transfer_reaction_index = ""
occupancy = "residential"
load_components = []
applied_area = 8.4822
start_loc = 0.1348
start_magnitude = 0.0932
end_loc = 10.8596
end_magnitude = 0.0932
