[element_attributes]
tag = "SJ0.0-5"
length = 11.2766
orientation = "horizontal"
vert_correspondent_below = []
vert_correspondent_above = []
horz_intersects_above = []
horz_intersects_below = [
    "WT0.0",
    "FB0.3",
]

[element_attributes.user_defined]

[element_geometry]
geometry = "LINESTRING (18.0422 18.5681, 18.0422 29.8447)"
supports = [
    { location = 0.1377, fixity = "pin" },
    { location = 10.8596, fixity = "roller" },
]

[loads]
point_loads = []

[[loads.distributed_loads]]
transfer_source = ""
transfer_reaction_index = ""
occupancy = "residential"
load_components = []
applied_area = 40.4496
start_loc = 0.1377
start_magnitude = 0.0933
end_loc = 10.8596
end_magnitude = 0.0933
