[element_attributes]
tag = "CB0.3"
orientation = "vertical"

[element_attributes.length]

[element_geometry]
geometry = "POLYGON ((33.0483 33.2458, 33.0483 33.9251, 33.7276 33.9251, 33.7276 33.2458, 33.0483 33.2458))"
supports = []

[loads]
point_loads = []
distributed_loads = []
