[element_attributes]
tag = "CB0.4"
orientation = "vertical"

[element_attributes.length]

[element_geometry]
geometry = "POLYGON ((28.2097 33.1702, 28.2097 33.8495, 28.8891 33.8495, 28.8891 33.1702, 28.2097 33.1702))"
supports = []

[loads]
point_loads = []
distributed_loads = []
