[element_attributes]
tag = "CB0.6"
orientation = "vertical"

[element_attributes.length]

[element_geometry]
geometry = "POLYGON ((14.7742 33.1365, 14.7742 33.8159, 15.4535 33.8159, 15.4535 33.1365, 14.7742 33.1365))"
supports = []

[loads]
point_loads = []
distributed_loads = []
