[element_attributes]
tag = "CB0.5"
orientation = "vertical"

[element_attributes.length]

[element_geometry]
geometry = "POLYGON ((14.8897 22.0142, 14.8897 22.6935, 15.569 22.6935, 15.569 22.0142, 14.8897 22.0142))"
supports = []

[loads]
point_loads = []
distributed_loads = []
