[element_attributes]
tag = "CB1.2"
orientation = "vertical"

[element_attributes.length]

[element_geometry]
geometry = "POLYGON ((19.7544 22.0277, 19.7544 22.7071, 20.4338 22.7071, 20.4338 22.0277, 19.7544 22.0277))"
supports = []

[loads]
point_loads = []
distributed_loads = []
