[element_attributes]
tag = "CT0.2"
orientation = "vertical"

[element_attributes.length]

[element_geometry]
geometry = "POLYGON ((18.8018 20.8077, 18.8018 21.331, 19.3819 21.331, 19.3819 20.8077, 18.8018 20.8077))"
supports = []

[loads]
distributed_loads = []

[[loads.point_loads]]
location = []
magnitude = 0
transfer_source = "FB0.1"
transfer_reaction_idx = 1
direction = "gravity"
