[element_attributes]
tag = "CT1.2"
orientation = "vertical"

[element_attributes.length]

[element_geometry]
geometry = "POLYGON ((33.0766 21.9779, 33.0766 22.6572, 33.7559 22.6572, 33.7559 21.9779, 33.0766 21.9779))"
supports = []

[loads]
distributed_loads = []

[[loads.point_loads]]
location = []
magnitude = 0
transfer_source = "FB1.1"
transfer_reaction_idx = 2
direction = "gravity"
