[element_attributes]
tag = "CT1.1"
orientation = "vertical"

[element_attributes.length]

[element_geometry]
geometry = "POLYGON ((22.583 21.9779, 22.583 22.6572, 23.2623 22.6572, 23.2623 21.9779, 22.583 21.9779))"
supports = []

[loads]
distributed_loads = []

[[loads.point_loads]]
location = []
magnitude = 0
transfer_source = "FB1.1"
transfer_reaction_idx = 1
direction = "gravity"
