[element_attributes]
tag = "CT1.3"
orientation = "vertical"

[element_attributes.length]

[element_geometry]
geometry = "POLYGON ((33.0483 33.2458, 33.0483 33.9251, 33.7276 33.9251, 33.7276 33.2458, 33.0483 33.2458))"
supports = []

[loads]
distributed_loads = []

[[loads.point_loads]]
location = []
magnitude = 0
transfer_source = "FB1.2"
transfer_reaction_idx = 2
direction = "gravity"
