[element_attributes]
tag = "CT1.5"
orientation = "vertical"

[element_attributes.length]

[element_geometry]
geometry = "POLYGON ((28.2097 33.1702, 28.2097 33.8495, 28.8891 33.8495, 28.8891 33.1702, 28.2097 33.1702))"
supports = []

[loads]
distributed_loads = []

[[loads.point_loads]]
location = []
magnitude = 0
transfer_source = "FB1.2"
transfer_reaction_idx = 1
direction = "gravity"
