[element_attributes]
tag = "CT1.4"
orientation = "vertical"

[element_attributes.length]

[element_geometry]
geometry = "POLYGON ((14.7742 33.1365, 14.7742 33.8159, 15.4535 33.8159, 15.4535 33.1365, 14.7742 33.1365))"
supports = []

[loads]
distributed_loads = []

[[loads.point_loads]]
location = []
magnitude = 0
transfer_source = "FB1.2"
transfer_reaction_idx = 0
direction = "gravity"
