[element_attributes]
tag = "CT2.2"
orientation = "vertical"

[element_attributes.length]

[element_geometry]
geometry = "POLYGON ((19.7544 22.0277, 19.7544 22.7071, 20.4338 22.7071, 20.4338 22.0277, 19.7544 22.0277))"
supports = []

[loads]
distributed_loads = []

[[loads.point_loads]]
location = []
magnitude = 0
transfer_source = "FB2.1"
transfer_reaction_idx = 0
direction = "gravity"
