[element_attributes]
tag = "FB0.1"
length = 10.269
orientation = "horizontal"

[element_geometry]
geometry = "LINESTRING (9.1991 20.907, 19.4681 20.907)"
supports = [
    { location = 0.25450000000000017, fixity = "pin" },
    { location = 9.892750000000001, fixity = "roller" },
]

[loads]
distributed_loads = []

[[loads.point_loads]]
location = 0.0
magnitude = 0
transfer_source = "J0.1-0"
transfer_reaction_idx = 1
direction = "gravity"

[[loads.point_loads]]
location = 1.3330000035813292
magnitude = 0
transfer_source = "J0.1-1"
transfer_reaction_idx = 1
direction = "gravity"

[[loads.point_loads]]
location = 2.6660000071626566
magnitude = 0
transfer_source = "J0.1-2"
transfer_reaction_idx = 1
direction = "gravity"

[[loads.point_loads]]
location = 3.999000010743984
magnitude = 0
transfer_source = "J0.1-3"
transfer_reaction_idx = 1
direction = "gravity"

[[loads.point_loads]]
location = 5.3320000143253115
magnitude = 0
transfer_source = "J0.1-4"
transfer_reaction_idx = 1
direction = "gravity"

[[loads.point_loads]]
location = 6.665000017906641
magnitude = 0
transfer_source = "J0.1-5"
transfer_reaction_idx = 1
direction = "gravity"

[[loads.point_loads]]
location = 7.998000021487966
magnitude = 0
transfer_source = "J0.1-6"
transfer_reaction_idx = 1
direction = "gravity"

[[loads.point_loads]]
location = 9.331000025069292
magnitude = 0
transfer_source = "J0.1-7"
transfer_reaction_idx = 1
direction = "gravity"

[[loads.point_loads]]
location = 10.115791320920684
magnitude = 0
transfer_source = "J0.1-8"
transfer_reaction_idx = 1
direction = "gravity"
