[element_attributes]
tag = "FB0.2"
length = 10.4843
orientation = "horizontal"

[element_geometry]
geometry = "LINESTRING (8.8301 27.6096, 19.3144 27.6096)"
supports = [
    { location = 0.31209999999999916, fixity = "pin" },
    { location = 9.9717, fixity = "roller" },
]

[loads]
distributed_loads = []

[[loads.point_loads]]
location = 0.3685086790793157
magnitude = 0
transfer_source = "J0.1-0"
transfer_reaction_idx = 0
direction = "gravity"

[[loads.point_loads]]
location = 1.7015086826606431
magnitude = 0
transfer_source = "J0.1-1"
transfer_reaction_idx = 0
direction = "gravity"

[[loads.point_loads]]
location = 3.0345086862419723
magnitude = 0
transfer_source = "J0.1-2"
transfer_reaction_idx = 0
direction = "gravity"

[[loads.point_loads]]
location = 4.367508689823298
magnitude = 0
transfer_source = "J0.1-3"
transfer_reaction_idx = 0
direction = "gravity"

[[loads.point_loads]]
location = 5.700508693404627
magnitude = 0
transfer_source = "J0.1-4"
transfer_reaction_idx = 0
direction = "gravity"

[[loads.point_loads]]
location = 7.033508696985955
magnitude = 0
transfer_source = "J0.1-5"
transfer_reaction_idx = 0
direction = "gravity"

[[loads.point_loads]]
location = 8.366508700567282
magnitude = 0
transfer_source = "J0.1-6"
transfer_reaction_idx = 0
direction = "gravity"

[[loads.point_loads]]
location = 9.699508704148608
magnitude = 0
transfer_source = "J0.1-7"
transfer_reaction_idx = 0
direction = "gravity"

[[loads.point_loads]]
location = 10.4843
magnitude = 0
transfer_source = "J0.1-8"
transfer_reaction_idx = 0
direction = "gravity"
