[element_attributes]
tag = "FB1.2"
length = 18.282
orientation = "horizontal"

[element_geometry]
geometry = "LINESTRING (33.4133 33.4711, 15.1313 33.4711)"
supports = [
    { location = 17.916999999999998, fixity = "pin" },
    { location = 0.3222000000000005, fixity = "roller" },
    { location = 13.418099999999999, fixity = "roller" },
]

[loads]
distributed_loads = []

[[loads.point_loads]]
location = 4.962800000000001
magnitude = 0
transfer_source = "CB1.1"
transfer_reaction_idx = 0
direction = "gravity"

[[loads.point_loads]]
location = 0.024200000000000443
magnitude = 0
transfer_source = "J1.1-0"
transfer_reaction_idx = 1
direction = "gravity"

[[loads.point_loads]]
location = 1.3575000000000017
magnitude = 0
transfer_source = "J1.1-1"
transfer_reaction_idx = 1
direction = "gravity"

[[loads.point_loads]]
location = 2.6907999999999994
magnitude = 0
transfer_source = "J1.1-2"
transfer_reaction_idx = 1
direction = "gravity"

[[loads.point_loads]]
location = 4.024100000000001
magnitude = 0
transfer_source = "J1.1-3"
transfer_reaction_idx = 1
direction = "gravity"

[[loads.point_loads]]
location = 5.357400000000002
magnitude = 0
transfer_source = "J1.1-4"
transfer_reaction_idx = 1
direction = "gravity"

[[loads.point_loads]]
location = 6.6907
magnitude = 0
transfer_source = "J1.1-5"
transfer_reaction_idx = 1
direction = "gravity"

[[loads.point_loads]]
location = 8.023999999999997
magnitude = 0
transfer_source = "J1.1-6"
transfer_reaction_idx = 1
direction = "gravity"

[[loads.point_loads]]
location = 9.357299999999999
magnitude = 0
transfer_source = "J1.1-7"
transfer_reaction_idx = 1
direction = "gravity"

[[loads.point_loads]]
location = 10.6906
magnitude = 0
transfer_source = "J1.1-8"
transfer_reaction_idx = 1
direction = "gravity"

[[loads.point_loads]]
location = 12.023899999999998
magnitude = 0
transfer_source = "J1.1-9"
transfer_reaction_idx = 1
direction = "gravity"

[[loads.point_loads]]
location = 13.357199999999995
magnitude = 0
transfer_source = "J1.1-10"
transfer_reaction_idx = 1
direction = "gravity"

[[loads.point_loads]]
location = 14.690499999999997
magnitude = 0
transfer_source = "J1.1-11"
transfer_reaction_idx = 1
direction = "gravity"

[[loads.point_loads]]
location = 16.023799999999998
magnitude = 0
transfer_source = "J1.1-12"
transfer_reaction_idx = 1
direction = "gravity"

[[loads.point_loads]]
location = 17.3571
magnitude = 0
transfer_source = "J1.1-13"
transfer_reaction_idx = 1
direction = "gravity"

[[loads.point_loads]]
location = 18.282
magnitude = 0
transfer_source = "J1.1-14"
transfer_reaction_idx = 1
direction = "gravity"
