[element_attributes]
tag = "FB1.1"
length = 18.282100000000003
orientation = "horizontal"

[element_geometry]
geometry = "LINESTRING (33.4376 22.4091, 15.1555 22.4091)"
supports = [
    { location = 7.767149999999997, fixity = "pin" },
    { location = 17.9211, fixity = "roller" },
    { location = 0.41350000000000087, fixity = "roller" },
]

[loads]
distributed_loads = []

[[loads.point_loads]]
location = 4.938600000000001
magnitude = 0
transfer_source = "CB1.2"
transfer_reaction_idx = 0
direction = "gravity"

[[loads.point_loads]]
location = 0.0
magnitude = 0
transfer_source = "J1.1-0"
transfer_reaction_idx = 0
direction = "gravity"

[[loads.point_loads]]
location = 1.3333000000000013
magnitude = 0
transfer_source = "J1.1-1"
transfer_reaction_idx = 0
direction = "gravity"

[[loads.point_loads]]
location = 2.666599999999999
magnitude = 0
transfer_source = "J1.1-2"
transfer_reaction_idx = 0
direction = "gravity"

[[loads.point_loads]]
location = 3.9999000000000002
magnitude = 0
transfer_source = "J1.1-3"
transfer_reaction_idx = 0
direction = "gravity"

[[loads.point_loads]]
location = 5.3332000000000015
magnitude = 0
transfer_source = "J1.1-4"
transfer_reaction_idx = 0
direction = "gravity"

[[loads.point_loads]]
location = 6.666499999999999
magnitude = 0
transfer_source = "J1.1-5"
transfer_reaction_idx = 0
direction = "gravity"

[[loads.point_loads]]
location = 7.999799999999997
magnitude = 0
transfer_source = "J1.1-6"
transfer_reaction_idx = 0
direction = "gravity"

[[loads.point_loads]]
location = 9.333099999999998
magnitude = 0
transfer_source = "J1.1-7"
transfer_reaction_idx = 0
direction = "gravity"

[[loads.point_loads]]
location = 10.6664
magnitude = 0
transfer_source = "J1.1-8"
transfer_reaction_idx = 0
direction = "gravity"

[[loads.point_loads]]
location = 11.999699999999997
magnitude = 0
transfer_source = "J1.1-9"
transfer_reaction_idx = 0
direction = "gravity"

[[loads.point_loads]]
location = 13.332999999999995
magnitude = 0
transfer_source = "J1.1-10"
transfer_reaction_idx = 0
direction = "gravity"

[[loads.point_loads]]
location = 14.666299999999996
magnitude = 0
transfer_source = "J1.1-11"
transfer_reaction_idx = 0
direction = "gravity"

[[loads.point_loads]]
location = 15.999599999999997
magnitude = 0
transfer_source = "J1.1-12"
transfer_reaction_idx = 0
direction = "gravity"

[[loads.point_loads]]
location = 17.3329
magnitude = 0
transfer_source = "J1.1-13"
transfer_reaction_idx = 0
direction = "gravity"

[[loads.point_loads]]
location = 18.2578
magnitude = 0
transfer_source = "J1.1-14"
transfer_reaction_idx = 0
direction = "gravity"
