[element_attributes]
tag = "FB2.1"
length = 11.113499999999998
orientation = "horizontal"

[element_geometry]
geometry = "LINESTRING (20.1358 33.5226, 20.1358 22.4091)"
supports = [
    { location = 10.732099999999999, fixity = "pin" },
    { location = 0.2980000000000018, fixity = "roller" },
]

[loads]
distributed_loads = []

[[loads.point_loads]]
location = 0.0
magnitude = 0
transfer_source = "J2.1-0"
transfer_reaction_idx = 0
direction = "gravity"

[[loads.point_loads]]
location = 1.3332999999999977
magnitude = 0
transfer_source = "J2.1-1"
transfer_reaction_idx = 0
direction = "gravity"

[[loads.point_loads]]
location = 2.6665999999999954
magnitude = 0
transfer_source = "J2.1-2"
transfer_reaction_idx = 0
direction = "gravity"

[[loads.point_loads]]
location = 3.999899999999993
magnitude = 0
transfer_source = "J2.1-3"
transfer_reaction_idx = 0
direction = "gravity"

[[loads.point_loads]]
location = 5.333199999999994
magnitude = 0
transfer_source = "J2.1-4"
transfer_reaction_idx = 0
direction = "gravity"

[[loads.point_loads]]
location = 6.666499999999996
magnitude = 0
transfer_source = "J2.1-5"
transfer_reaction_idx = 0
direction = "gravity"

[[loads.point_loads]]
location = 7.999799999999993
magnitude = 0
transfer_source = "J2.1-6"
transfer_reaction_idx = 0
direction = "gravity"

[[loads.point_loads]]
location = 9.333099999999995
magnitude = 0
transfer_source = "J2.1-7"
transfer_reaction_idx = 0
direction = "gravity"

[[loads.point_loads]]
location = 10.666399999999992
magnitude = 0
transfer_source = "J2.1-8"
transfer_reaction_idx = 0
direction = "gravity"

[[loads.point_loads]]
location = 11.113499999999998
magnitude = 0
transfer_source = "J2.1-9"
transfer_reaction_idx = 0
direction = "gravity"
