[element_attributes]
tag = "J1.1-2"
length = 11.104499999999998
orientation = "horizontal"

[element_geometry]
geometry = "LINESTRING (17.8221 22.4091, 17.8221 33.5136)"
supports = [
    { location = 0.0, fixity = "pin" },
    { location = 11.062000000000001, fixity = "roller" },
]

[loads]
point_loads = []

[[loads.distributed_loads]]
occupancy = "residential"
load_components = []
applied_area = 14.805629850001344
start_loc = 0
start_magnitude = 0.090054
end_loc = 11.104499999998998
end_magnitude = 0.090054

[[loads.distributed_loads]]
occupancy = "big stuff"
load_components = []
applied_area = 3.2682280800576415
start_loc = 2.390900000001002
start_magnitude = 0.123578
end_loc = 9.615100000000002
end_magnitude = 0.153222

[[loads.distributed_loads]]
occupancy = "big stuff"
load_components = []
applied_area = 0.0005502853483513148
start_loc = 9.615100000001002
start_magnitude = 0.153222
end_loc = 9.617297406032746
end_magnitude = 0.0
