[element_attributes]
tag = "J1.1-14"
length = 11.104499999999998
orientation = "horizontal"

[element_geometry]
geometry = "LINESTRING (33.4133 22.4091, 33.4133 33.5136)"
supports = [
    { location = 0.0, fixity = "pin" },
    { location = 11.062000000000001, fixity = "roller" },
]

[loads]
point_loads = []

[[loads.distributed_loads]]
occupancy = "residential"
load_components = []
applied_area = 5.135276025000507
start_loc = 0
start_magnitude = 0.090054
end_loc = 11.104499999998994
end_magnitude = 0.090054
