[element_attributes]
tag = "J1.1-0"
length = 11.104499999999998
orientation = "horizontal"

[element_geometry]
geometry = "LINESTRING (15.1555 22.4091, 15.1555 33.5136)"
supports = [
    { location = 0.0, fixity = "pin" },
    { location = 11.062000000000001, fixity = "roller" },
]

[loads]
point_loads = []

[[loads.distributed_loads]]
occupancy = "residential"
load_components = []
applied_area = 7.402814925000672
start_loc = 0
start_magnitude = 0.090054
end_loc = 11.104499999998998
end_magnitude = 0.090054
