[element_attributes]
tag = "J2.1-9"
length = 16.960700000000003
orientation = "horizontal"

[element_geometry]
geometry = "LINESTRING (16.4769 33.5226, 33.4376 33.5226)"
supports = [
    { location = 3.658899999999999, fixity = "pin" },
    { location = 16.717, fixity = "roller" },
]

[loads]
point_loads = []

[[loads.distributed_loads]]
occupancy = "roof"
load_components = []
applied_area = 3.7915644850002748
start_loc = 0
start_magnitude = 0.05896
end_loc = 16.960699999999004
end_magnitude = 0.05896
