[element_attributes]
tag = "WB0.1"
orientation = "vertical"

[element_attributes.length]

[element_geometry]
geometry = "POLYGON ((33.1515 22.6864, 33.1515 33.2909, 33.7444 33.2909, 33.7444 22.6864, 33.1515 22.6864))"
supports = []

[loads]
point_loads = []
distributed_loads = []
