[element_attributes]
tag = "WT1.1"
orientation = "vertical"

[element_attributes.length]

[element_geometry]
geometry = "POLYGON ((33.2727 22.7114, 33.2727 33.2909, 33.6378 33.2909, 33.6378 22.7114, 33.2727 22.7114))"
supports = []

[loads]
point_loads = []
distributed_loads = []
