[element_attributes]
tag = "CT0.3"
orientation = "vertical"

[element_attributes.length]

[element_geometry]
geometry = "POLYGON ((8.8521 27.1918, 8.8521 27.715, 9.4323 27.715, 9.4323 27.1918, 8.8521 27.1918))"
supports = []

[loads]
distributed_loads = []

[[loads.point_loads]]
location = []
magnitude = 0
transfer_source = "FB0.2"
transfer_reaction_idx = 0
direction = "gravity"
