[element_attributes]
tag = "CT0.1"
orientation = "vertical"

[element_attributes.length]

[element_geometry]
geometry = "POLYGON ((8.8735 20.765, 8.8735 21.2883, 9.4536 21.2883, 9.4536 20.765, 8.8735 20.765))"
supports = []

[loads]
distributed_loads = []

[[loads.point_loads]]
location = []
magnitude = 0
transfer_source = "FB0.1"
transfer_reaction_idx = 0
direction = "gravity"
