[element_attributes]
tag = "CT0.4"
orientation = "vertical"

[element_attributes.length]

[element_geometry]
geometry = "POLYGON ((18.8018 27.1491, 18.8018 27.6723, 19.3819 27.6723, 19.3819 27.1491, 18.8018 27.1491))"
supports = []

[loads]
distributed_loads = []

[[loads.point_loads]]
location = []
magnitude = 0
transfer_source = "FB0.2"
transfer_reaction_idx = 1
direction = "gravity"
