[element_attributes]
tag = "CT1.2"
orientation = "vertical"
vert_correspondent_below = [
    "CB0.2",
]
vert_correspondent_above = []
horz_intersects_above = []
horz_intersects_below = []

[element_attributes.length]

[element_attributes.user_defined]

[element_geometry]
geometry = "POLYGON ((33.048 33.246, 33.048 33.925, 33.728 33.925, 33.728 33.246, 33.048 33.246))"
supports = []

[loads]
point_loads = []
distributed_loads = []
