[element_attributes]
tag = "CB3.1"
orientation = "vertical"
vert_correspondent_below = []
vert_correspondent_above = [
    "CT4.1",
]
horz_intersects_above = []
horz_intersects_below = [
    "FB3.0",
]

[element_attributes.length]

[element_attributes.user_defined]

[element_geometry]
geometry = "POLYGON ((19.754 22.028, 19.754 22.707, 20.434 22.707, 20.434 22.028, 19.754 22.028))"
supports = []

[loads]
distributed_loads = []

[[loads.point_loads]]
location = []
magnitude = 0.0
transfer_source = "CT4.1"
transfer_reaction_index = 0
direction = "gravity"
