[element_attributes]
tag = "CT3.0"
orientation = "vertical"
vert_correspondent_below = [
    "CT2.0",
]
vert_correspondent_above = []
horz_intersects_above = [
    "FB3.0",
]
horz_intersects_below = []

[element_attributes.length]

[element_attributes.user_defined]

[element_geometry]
geometry = "POLYGON ((22.583 21.978, 22.583 22.657, 23.262 22.657, 23.262 21.978, 22.583 21.978))"
supports = []

[loads]
distributed_loads = []

[[loads.point_loads]]
location = 0.0
magnitude = 0.0
transfer_source = "FB3.0"
transfer_reaction_index = 1
direction = "gravity"
