[element_attributes]
tag = "FB1.3"
length = 10.836
orientation = "horizontal"
vert_correspondent_below = []
vert_correspondent_above = []
horz_intersects_above = [
    "J1.1",
]
horz_intersects_below = [
    "CT1.4",
    "CT1.6",
]

[element_attributes.user_defined]

[element_geometry]
geometry = "LINESTRING (28.574 33.564, 28.626 22.727)"
supports = [
    { location = 0.393, fixity = "pin" },
    { location = 10.785, fixity = "roller" },
]

[loads]
point_loads = []

[[loads.distributed_loads]]
transfer_source = "J1.1"
transfer_reaction_index = 0
transfer_source_start_extent = []
transfer_source_end_extent = []
occupancy = ""
applied_area = 0.0
start_loc = 5.347
start_magnitude = 1.0
end_loc = 6.347
end_magnitude = 1.0
direction = "gravity"

[loads.distributed_loads.load_components]
