[element_attributes]
tag = "FB3.0"
length = 18.282
orientation = "horizontal"
vert_correspondent_below = []
vert_correspondent_above = []
horz_intersects_above = [
    "CB3.1",
    "J3.0",
]
horz_intersects_below = [
    "CT3.0",
    "CT3.1",
    "CT3.5",
]

[element_attributes.user_defined]

[element_geometry]
geometry = "LINESTRING (33.438 22.409, 15.156 22.409)"
supports = [
    { location = 7.767, fixity = "pin" },
    { location = 17.921, fixity = "roller" },
    { location = 0.414, fixity = "roller" },
]

[[loads.point_loads]]
location = 4.939
magnitude = 0.0
transfer_source = "CB3.1"
transfer_reaction_index = 0
direction = "gravity"

[[loads.distributed_loads]]
transfer_source = "J3.0"
transfer_reaction_index = 0
transfer_source_start_extent = []
transfer_source_end_extent = []
occupancy = ""
applied_area = 0.0
start_loc = 8.79
start_magnitude = 1.0
end_loc = 9.79
end_magnitude = 1.0
direction = "gravity"

[loads.distributed_loads.load_components]
