[element_attributes]
tag = "CPL0.6"
orientation = "vertical"
vert_correspondent_below = []
vert_correspondent_above = [
    "CT1.3",
]
horz_intersects_above = []
horz_intersects_below = []

[element_attributes.length]

[element_attributes.user_defined]

[element_geometry]
geometry = "POLYGON ((15.1768 41.4451, 14.5524 41.4451, 14.5524 42.0239, 15.1768 42.0239, 15.1768 41.4451))"
supports = []

[loads]
distributed_loads = []

[[loads.point_loads]]
location = []
magnitude = 0.0
transfer_source = "CT1.3"
transfer_reaction_index = 0
direction = "gravity"
