[element_attributes]
tag = "CT0.5"
orientation = "vertical"
vert_correspondent_below = []
vert_correspondent_above = []
horz_intersects_above = [
    "FB0.1",
]
horz_intersects_below = []

[element_attributes.length]

[element_attributes.user_defined]

[element_geometry]
geometry = "POLYGON ((15.2691 38.3062, 14.6447 38.3062, 14.6447 38.8912, 15.2691 38.8912, 15.2691 38.3062))"
supports = []

[loads]
distributed_loads = []

[[loads.point_loads]]
location = 0.0
magnitude = 0.0
transfer_source = "FB0.1"
transfer_reaction_index = 0
direction = "gravity"
