[element_attributes]
tag = "CT1.1"
orientation = "vertical"
vert_correspondent_below = [
    "CPL0.2",
]
vert_correspondent_above = []
horz_intersects_above = [
    "FB1.0",
]
horz_intersects_below = []

[element_attributes.length]

[element_attributes.user_defined]

[element_geometry]
geometry = "POLYGON ((44.788 50.0382, 44.1524 50.0382, 44.1524 50.6171, 44.788 50.6171, 44.788 50.0382))"
supports = []

[loads]
distributed_loads = []

[[loads.point_loads]]
location = 0.0
magnitude = 0.0
transfer_source = "FB1.0"
transfer_reaction_index = 1
direction = "gravity"
