[element_attributes]
tag = "J0.2"
length = 12.0092
orientation = "horizontal"
vert_correspondent_below = []
vert_correspondent_above = []
horz_intersects_above = []
horz_intersects_below = [
    "FB0.0",
    "FB0.3",
]

[element_attributes.user_defined]

[element_geometry]
geometry = "LINESTRING (35.4417 26.8638, 35.4417 38.873)"
supports = [
    { location = 11.7937, fixity = "pin" },
    { location = 0.0417, fixity = "roller" },
]

[loads]
point_loads = []

[[loads.distributed_loads]]
transfer_source = ""
transfer_reaction_index = ""
occupancy = "e"
load_components = []
applied_area = 12.0092
start_loc = 0
start_magnitude = 0.0833
end_loc = 12.0092
end_magnitude = 0.0833
