[element_attributes]
tag = "J1.0"
length = 14.1638
orientation = "horizontal"
vert_correspondent_below = []
vert_correspondent_above = []
horz_intersects_above = []
horz_intersects_below = [
    "FB1.0",
    "FB1.2",
]

[element_attributes.user_defined]

[element_geometry]
geometry = "LINESTRING (34.8069 38.2628, 34.8069 52.4266)"
supports = [
    { location = 11.9697, fixity = "pin" },
    { location = 0.3383, fixity = "roller" },
]

[loads]
point_loads = []

[[loads.distributed_loads]]
transfer_source = ""
transfer_reaction_index = ""
occupancy = "f"
load_components = []
applied_area = 14.1638
start_loc = 0
start_magnitude = 0.0706
end_loc = 14.1638
end_magnitude = 0.0706
