[element_attributes]
tag = "W0.2"
length = 6.5781
orientation = "vertical"
vert_correspondent_below = []
vert_correspondent_above = []
horz_intersects_above = [
    "J0.3",
    "WLL0.0",
]
horz_intersects_below = []

[element_attributes.user_defined]

[element_geometry]
geometry = "POLYGON ((44.6646 26.6041, 38.0865 26.6041, 38.0865 27.1072, 44.6646 27.1072, 44.6646 26.6041))"
supports = []

[loads]
point_loads = []

[[loads.distributed_loads]]
transfer_source = "J0.3"
transfer_reaction_index = 0
transfer_source_start_extent = []
transfer_source_end_extent = []
occupancy = ""
applied_area = 0.0
start_loc = 2.528
start_magnitude = 1.0
end_loc = 3.528
end_magnitude = 1.0
direction = "gravity"

[loads.distributed_loads.load_components]

[[loads.distributed_loads]]
transfer_source = "WLL0.0"
transfer_reaction_index = 0
transfer_source_start_extent = 23.4239
transfer_source_end_extent = 30.002
occupancy = ""
applied_area = 0.0
start_loc = 0.032
start_magnitude = 1.0
end_loc = 6.5782
end_magnitude = 1.0
direction = "gravity"

[loads.distributed_loads.load_components]
