[element_attributes]
tag = "CT1.7"
length = 0.665
orientation = "vertical"
vert_correspondent_below = [
    "WB0.0",
]
vert_correspondent_above = []
horz_intersects_above = []
horz_intersects_below = []

[element_attributes.user_defined]

[element_geometry]
geometry = "POLYGON ((33.217 27.418, 33.217 28.057, 33.882 28.057, 33.882 27.418, 33.217 27.418))"
supports = []

[loads]
point_loads = []
distributed_loads = []
