[element_attributes]
tag = "CT3.2"
orientation = "vertical"
vert_correspondent_below = [
    "WB2.0",
]
vert_correspondent_above = []
horz_intersects_above = [
    "FB3.1",
]
horz_intersects_below = []

[element_attributes.length]

[element_attributes.user_defined]

[element_geometry]
geometry = "POLYGON ((33.085 33.04, 33.085 33.719, 33.764 33.719, 33.764 33.04, 33.085 33.04))"
supports = []

[loads]
distributed_loads = []

[[loads.point_loads]]
location = 0.0
magnitude = 0.0
transfer_source = "FB3.1"
transfer_reaction_index = 2
direction = "gravity"
