[element_attributes]
tag = "CT4.0"
orientation = "vertical"
vert_correspondent_below = [
    "CB3.0",
]
vert_correspondent_above = []
horz_intersects_above = [
    "FB4.0",
]
horz_intersects_below = []

[element_attributes.length]

[element_attributes.user_defined]

[element_geometry]
geometry = "POLYGON ((19.754 33.141, 19.754 33.821, 20.434 33.821, 20.434 33.141, 19.754 33.141))"
supports = []

[loads]
distributed_loads = []

[[loads.point_loads]]
location = 0.0
magnitude = 0.0
transfer_source = "FB4.0"
transfer_reaction_index = 1
direction = "gravity"
