[element_attributes]
tag = "FB1.0"
length = 4.857
orientation = "horizontal"
vert_correspondent_below = []
vert_correspondent_above = []
horz_intersects_above = []
horz_intersects_below = [
    "CT1.1",
    "CT1.6",
]

[element_attributes.user_defined]

[element_geometry]
geometry = "LINESTRING (33.336 22.358, 28.479 22.322)"
supports = [
    { location = 4.594, fixity = "pin" },
    { location = 0.666, fixity = "roller" },
]

[loads]
point_loads = []

[[loads.distributed_loads]]
transfer_source = ""
transfer_reaction_index = ""
occupancy = "residential"
load_components = []
applied_area = 0.0
start_loc = 0
start_magnitude = 0.201
end_loc = 0.0
end_magnitude = 0.201

[[loads.distributed_loads]]
transfer_source = ""
transfer_reaction_index = ""
occupancy = "residential"
load_components = []
applied_area = 4.077
start_loc = 0
start_magnitude = 0.201
end_loc = 4.857
end_magnitude = 0.21
