[element_attributes]
tag = "FB2.2"
length = 18.868
orientation = "horizontal"
vert_correspondent_below = []
vert_correspondent_above = []
horz_intersects_above = [
    "J2.0",
    "WB2.0",
]
horz_intersects_below = [
    "FB2.3",
    "FB2.4",
]

[element_attributes.user_defined]

[element_geometry]
geometry = "LINESTRING (33.723 27.863, 14.854 27.863)"
supports = [
    { location = 18.715, fixity = "pin" },
    { location = 0.302, fixity = "roller" },
]

[loads]
point_loads = []

[[loads.distributed_loads]]
transfer_source = "J2.0"
transfer_reaction_index = 1
transfer_source_start_extent = []
transfer_source_end_extent = []
occupancy = ""
applied_area = 0.0
start_loc = 9.091
start_magnitude = 1.0
end_loc = 10.091
end_magnitude = 1.0
direction = "gravity"

[loads.distributed_loads.load_components]

[[loads.distributed_loads]]
transfer_source = "WB2.0"
transfer_reaction_index = 0
transfer_source_start_extent = 5.108
transfer_source_end_extent = 5.106
occupancy = ""
applied_area = 0.0
start_loc = 18.304
start_magnitude = 1.0
end_loc = 18.868
end_magnitude = 1.0
direction = "gravity"

[loads.distributed_loads.load_components]
