[element_attributes]
tag = "FB2.1"
length = 18.282
orientation = "horizontal"
vert_correspondent_below = []
vert_correspondent_above = []
horz_intersects_above = [
    "J2.0",
]
horz_intersects_below = [
    "CT2.2",
    "CT2.3",
    "CT2.4",
]

[element_attributes.user_defined]

[element_geometry]
geometry = "LINESTRING (33.259 33.453, 14.977 33.453)"
supports = [
    { location = 18.108, fixity = "pin" },
    { location = 0.477, fixity = "roller" },
    { location = 13.573, fixity = "roller" },
]

[loads]
point_loads = []

[[loads.distributed_loads]]
transfer_source = "J2.0"
transfer_reaction_index = 2
transfer_source_start_extent = []
transfer_source_end_extent = []
occupancy = ""
applied_area = 0.0
start_loc = 8.969
start_magnitude = 1.0
end_loc = 9.969
end_magnitude = 1.0
direction = "gravity"

[loads.distributed_loads.load_components]
