[element_attributes]
tag = "FB2.0"
length = 18.282
orientation = "horizontal"
vert_correspondent_below = []
vert_correspondent_above = []
horz_intersects_above = [
    "J2.0",
]
horz_intersects_below = [
    "CT2.0",
    "CT2.1",
    "CT2.5",
]

[element_attributes.user_defined]

[element_geometry]
geometry = "LINESTRING (33.474 22.3, 15.192 22.3)"
supports = [
    { location = 7.731, fixity = "pin" },
    { location = 17.885, fixity = "roller" },
    { location = 0.377, fixity = "roller" },
]

[loads]
point_loads = []

[[loads.distributed_loads]]
transfer_source = "J2.0"
transfer_reaction_index = 0
transfer_source_start_extent = []
transfer_source_end_extent = []
occupancy = ""
applied_area = 0.0
start_loc = 8.754
start_magnitude = 1.0
end_loc = 9.754
end_magnitude = 1.0
direction = "gravity"

[loads.distributed_loads.load_components]
