[element_attributes]
tag = "FB2.3"
length = 11.127203559295568
orientation = "horizontal"
vert_correspondent_below = []
vert_correspondent_above = []
horz_intersects_above = [
    "FB2.1",
    "FB2.2",
    "WB2.0",
]
horz_intersects_below = [
    "CT2.1",
    "CT2.2",
]

[element_geometry]
geometry = "LINESTRING (33.3943 22.5138, 33.4032 33.641)"
supports = [
    { location = 0.14340004586984884, fixity = "pin" },
    { location = 10.525903366955683, fixity = "roller" },
]

[[loads.point_loads]]
location = 10.957303504949074
magnitude = 0
transfer_source = "FB2.1"
transfer_reaction_index = 3
direction = "gravity"

[[loads.point_loads]]
location = 5.348801710938974
magnitude = 0
transfer_source = "FB2.2"
transfer_reaction_index = 1
direction = "gravity"

[[loads.distributed_loads]]
transfer_source = "WB2.0"
transfer_reaction_index = 0
occupancy = ""
applied_area = 0.0
start_loc = 0.2498000799043819
start_magnitude = 1.0
end_loc = 10.606703392801453
end_magnitude = 1.0
direction = "gravity"

[loads.distributed_loads.load_components]
