[element_attributes]
tag = "J1.1"
length = 7.745
orientation = "horizontal"
vert_correspondent_below = []
vert_correspondent_above = []
horz_intersects_above = []
horz_intersects_below = [
    "WT1.0",
    "FB1.3",
]

[element_attributes.user_defined]

[element_geometry]
geometry = "LINESTRING (28.346 28.844, 36.091 28.844)"
supports = [
    { location = 5.132, fixity = "pin" },
    { location = 0.251, fixity = "roller" },
]

[loads]
point_loads = []

[[loads.distributed_loads]]
transfer_source = ""
transfer_reaction_index = ""
occupancy = "residential"
load_components = []
applied_area = 5.448
start_loc = 0
start_magnitude = 0.184
end_loc = 5.448
end_magnitude = 0.184
